name: Bancend CD

on:
  push:
    branches:
      - feature/github-action
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - feature/github-action
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  cd:
    runs-on: landing-page-dev

    steps:
      - uses: actions/checkout@v3

      - name: Update Code
        run: |
          cd /home/evik.santika/kidsloop-ibas/backend
          git fetch
          git pull origin feature/github-action
          git status

      - name: Run Docker Compose
        run: docker-compose -f /home/evik.santika/kidsloop-ibas/backend/docker-compose-dev.yml up -d --build
      
      - name: Clean up
        run: docker system prune --force