name: cd

on:
  push:
    branches:
      - feature/github-action
  pull_request:
    branches:
      - feature/github-action
  workflow_dispatch:

jobs:
  cd:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Using runner hosted
        run: |
          cd /home/evik.santika/kidsloop-ibas/kidsloop_indonesia_b2c_automation
          git fetch
          git pull feature/github-action
          git status
          docker-compose -f local.yml up -d --build