name: cd

on:
  push:
    branches:
      - feature/github-action
  pull_request:
    branches:
      - feature/github-action
  workflow_dispatch:

jobs:
  cd:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Update Code
        run: |
          cd /home/evik.santika/kidsloop-ibas/kidsloop_indonesia_b2c_automation
          git fetch
          git pull origin feature/github-action
          git status

      - name: Run Docker Compose
        run: docker-compose -f /home/evik.santika/kidsloop-ibas/kidsloop_indonesia_b2c_automation/local.yml up -d --build